// library/src/scripts/react/Message.tsx
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import * as React from 'react';
import { buildClass, markdown } from 'biuty/react';

interface MessageProps {
  id: string;
  label?: string;
  modifiers?: string;
}

/**
 * Message field type.
 */
function Message({ id, label = '', modifiers = '' }: MessageProps): JSX.Element {
  return (
    <section
      id={id}
      dangerouslySetInnerHTML={{ __html: markdown(label as string, false) }}
      className={buildClass('ui-message', modifiers)}
    />
  );
}

export default React.memo(Message) as JSXElement;

// library/src/scripts/svelte/Message.svelte
<!-- Message field type. -->
<script lang="ts">
/**
 * Copyright (c) Openizr. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import { buildClass, markdown } from 'biuty/svelte';

export let label = '';
export let modifiers = '';
export let id: string | undefined;

// Enforces props default values.
$: label = label || '';
$: modifiers = modifiers || '';

$: parsedLabel = markdown(label, false);
$: className = buildClass('ui-message', modifiers);
</script>

<section {id} class={className}>
  {@html parsedLabel}
</section>
