// library/src/scripts/react/containers/Form.tsx
/**
 * Copyright (c) Matthieu Jabbour. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import * as React from 'react';
import Engine from 'scripts/core/Engine';
import useStore from 'diox/connectors/react';
import Step from 'scripts/react/components/Step';
import stepPropType from 'scripts/propTypes/step';
import PropTypes, { InferProps } from 'prop-types';
import { Components, UserAction } from 'scripts/types';
import configurationPropType from 'scripts/propTypes/configuration';

const propTypes = {
  activeStep: PropTypes.string,
  configuration: PropTypes.shape(configurationPropType).isRequired,
  customComponents: PropTypes.objectOf(PropTypes.func.isRequired),
};

const defaultProps = {
  activeStep: null,
  customComponents: {},
};

/**
 * Dynamic form.
 */
export default function Form(props: InferProps<typeof propTypes>): JSX.Element {
  const { configuration, customComponents, activeStep } = props;
  const [engine] = React.useState(() => new Engine(configuration));
  const [useCombiner, mutate] = useStore(engine.getStore());
  const [state] = useCombiner('steps');

  const onUserAction = (stepIndex: number, fieldId: string, userAction: UserAction): void => {
    mutate('userActions', 'ADD', { ...userAction, stepIndex, fieldId });
  };

  return (
    <form className="form">
      <div className="form__steps">

        {/* Steps. */}
        {state.steps.map((step: InferProps<typeof stepPropType>, index: number) => {
          const key = `${index}_${step.id}`;
          const isActive = (activeStep !== null)
            ? activeStep === step.id
            : index === state.steps.length - 1;

          return (
            <Step
              key={key}
              id={step.id}
              index={index}
              isActive={isActive}
              fields={step.fields}
              status={step.status}
              onUserAction={onUserAction}
              customComponents={customComponents as Components}
            />
          );
        })}

        {/* Step loader. */}
        {(state.loadingNextStep === true) ? <div className="ui-loader" /> : null}

      </div>
    </form>
  );
}

Form.propTypes = propTypes;
Form.defaultProps = defaultProps;
Form.displayName = 'Form';

// library/src/scripts/vue/containers/Form.vue
<template>
  <form class="form">
    <div class="form__steps">
      <!-- Steps. -->
      <Step
        v-for="(step, index) in steps"
        :id="step.id"
        :key="`${index}_${step.id}`"
        :index="index"
        :is-active="(activeStep !== null)
          ? activeStep === step.id
          : index === steps.length - 1"
        :fields="step.fields"
        :status="step.status"
        :custom-components="customComponents"
        @userAction="onUserAction"
      />

      <!-- Step loader. -->
      <div
        v-if="loadingNextStep === true"
        class="ui-loader"
      />
    </div>
  </form>
</template>

<script lang="ts">
/**
 * Copyright (c) Matthieu Jabbour. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import {
  Json,
  Field,
  Generic,
  FormValue,
  UserAction,
  Configuration,
} from 'scripts/types';
import Vue from 'vue';
import Engine from 'scripts/core/Engine';
import Step from 'scripts/vue/components/Step.vue';

interface Props {
  activeStep: string;
  configuration: Configuration;
  customComponents: {
    [type: string]: (field: Field, onUserAction: (newValue: FormValue) => void) => {
      name: string;
      props: Json;
      events: Json;
    };
  };
}

/**
 * Dynamic form.
 */
export default Vue.extend<Generic, Generic, Generic, Props>({
  $store: null,
  $subscription: null,
  components: { Step },
  props: {
    activeStep: {
      type: String,
      required: false,
      default: null,
    },
    configuration: {
      type: Object,
      required: true,
    },
    customComponents: {
      type: Object,
      required: false,
      default: () => ({}),
    },
  },
  data() {
    return {
      steps: [],
      loadingNextStep: true,
    };
  },
  mounted() {
    const engine = new Engine(this.configuration);
    this.$store = engine.getStore();
    this.$subscription = this.$store.subscribe('steps', (newState: Json) => {
      this.steps = newState.steps;
      this.loadingNextStep = newState.loadingNextStep;
    });
  },
  beforeDestroy(): void {
    this.$store.unsubscribe('steps', this.$subscription);
  },
  methods: {
    onUserAction(stepIndex: number, fieldId: string, userAction: UserAction): void {
      (this as Json).$store.mutate('userActions', 'ADD', { ...userAction, stepIndex, fieldId });
    },
  },
} as Json);
</script>
