// library/src/scripts/vue/components/Field.vue
<template>
  <component
    :is="component.name"
    v-if="component !== null"
    v-bind="component.props"
    v-on="Object.keys(component.events).reduce((events, event) => (
      (component.events[event] !== undefined)
        ? { ...events, [event]: component.events[event] }
        : events
    ), {})"
  />
</template>

<script lang="ts">
/**
 * Copyright (c) Matthieu Jabbour. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

/* eslint-disable vue/one-component-per-file */

import {
  UIRadio,
  UIButton,
  markdown,
  buildClass,
  UIDropdown,
  UICheckbox,
  UITextarea,
  UITextfield,
  UIFileUploader,
} from 'sonar-ui/vue';
import Vue from 'vue';
import { ExtendedVue } from 'vue/types/vue.d';
import { Field } from 'scripts/propTypes/field';
import { FormValue } from 'scripts/core/Engine';

type Generic = Record<string, FormValue>;
type Components = { [type: string]: Component; };
type Component = (field: Field, onUserAction: (type: 'click' | 'input', newValue: FormValue) => void) => FormValue;

interface Props {
  id: string;
  type: string;
  label: string;
  status: string;
  message: string;
  value: FormValue;
  options: FormValue;
  active: boolean;
  i18n: (label: string, values?: Record<string, string>) => string;
  customComponents: {
    [type: string]: (field: Field, onUserAction: (newValue: FormValue) => void) => {
      name: string;
      props: FormValue;
      events: FormValue;
    };
  };
}

Vue.component('Message', {
  props: {
    id: {
      type: String,
      required: true,
    },
    label: {
      type: String,
      required: false,
      default: '',
    },
    status: {
      type: String,
      required: true,
    },
    options: {
      type: Object,
      required: true,
    },
  },
  computed: {
    content(): string {
      return markdown(this.label || '', false);
    },
    className() {
      return buildClass('ui-message', `${this.status} ${this.options.modifiers || ''}`.split(' '));
    },
  },
  render(createElement) {
    return createElement('section', {
      attrs: {
        id: this.id,
        class: this.className,
      },
      domProps: {
        innerHTML: this.content,
      },
    });
  },
}) as ExtendedVue<Vue, Generic, Generic, Generic, Generic>;

/**
 * Built-in form components.
 */
const builtInComponents: Components = {
  Message: (field) => ({
    name: 'Message',
    props: {
      id: field.id,
      label: field.label,
      status: field.status,
      options: field.options,
    },
    events: {},
  }),
  Button: (field, onUserAction) => ({
    name: 'UIButton',
    props: {
      id: field.id,
      label: field.label,
      icon: field.options.icon,
      type: field.options.type,
      modifiers: `${field.status} ${field.options.modifiers || ''} `,
      iconPosition: field.options.iconPosition,
    },
    events: {
      click: (): void => onUserAction('input', true),
    },
  }),
  Textfield: (field, onUserAction) => ({
    name: 'UITextfield',
    props: {
      id: field.id,
      name: field.id,
      label: field.label,
      value: field.value,
      helper: field.message,
      min: field.options.min,
      max: field.options.max,
      step: field.options.step,
      icon: field.options.icon,
      size: field.options.size,
      type: field.options.type,
      readonly: field.options.readonly || field.active === false,
      transform: field.options.transform,
      maxlength: field.options.maxlength,
      placeholder: (field.options.placeholder !== undefined && field.options.placeholder !== null)
        ? (field.i18n as FormValue)(field.options.placeholder, field.options.formValues)
        : null,
      iconPosition: field.options.iconPosition,
      debounceTimeout: field.options.debounceTimeout || 100,
      modifiers: `${field.status} ${field.options.modifiers || ''} `,
    },
    events: {
      blur: field.options.onBlur,
      focus: field.options.onFocus,
      iconClick: field.options.onIconClick,
      change: (value): void => onUserAction('input', value),
    },
  }),
  Textarea: (field, onUserAction) => ({
    name: 'UITextarea',
    props: {
      id: field.id,
      name: field.id,
      label: field.label,
      value: field.value,
      helper: field.message,
      cols: field.options.cols,
      rows: field.options.rows,
      transform: field.options.transform,
      maxlength: field.options.maxlength,
      placeholder: (field.options.placeholder !== undefined && field.options.placeholder !== null)
        ? (field.i18n as FormValue)(field.options.placeholder, field.options.formValues)
        : null,
      autocomplete: field.options.autocomplete,
      debounceTimeout: field.options.debounceTimeout || 100,
      readonly: field.options.readonly || field.active === false,
      modifiers: `${field.status} ${field.options.modifiers || ''}`,
    },
    events: {
      blur: field.options.onBlur,
      focus: field.options.onFocus,
      change: (value): void => onUserAction('input', value),
    },
  }),
  FileUploader: (field, onUserAction) => ({
    name: 'UIFileUploader',
    props: {
      id: field.id,
      name: field.id,
      label: field.label,
      value: field.value,
      helper: field.message,
      icon: field.options.icon,
      placeholder: (field.options.placeholder !== undefined && field.options.placeholder !== null)
        ? (field.i18n as FormValue)(field.options.placeholder, field.options.formValues)
        : null,
      iconPosition: field.options.iconPosition,
      modifiers: `${field.status} ${field.options.modifiers || ''}`,
    },
    events: {
      focus: field.options.onFocus,
      change: (value): void => onUserAction('input', value),
    },
  }),
  Dropdown: (field, onUserAction) => ({
    name: 'UIDropdown',
    props: {
      id: field.id,
      name: field.id,
      label: field.label,
      value: field.value,
      helper: field.message,
      icon: field.options.icon,
      options: field.options.options.map((option: FormValue) => ((option.label !== undefined)
        ? ({ ...option, label: (field.i18n as FormValue)(option.label, field.options.formValues) })
        : option)),
      multiple: field.options.multiple,
      modifiers: `${field.status} ${field.options.modifiers || ''}`,
    },
    events: {
      focus: field.options.onFocus,
      change: (value): void => onUserAction('input', value),
    },
  }),
  Checkbox: (field, onUserAction) => ({
    name: 'UICheckbox',
    props: {
      id: field.id,
      name: field.id,
      label: field.label,
      value: field.value,
      helper: field.message,
      options: field.options.options.map((option: FormValue) => ((option.label !== undefined)
        ? ({ ...option, label: (field.i18n as FormValue)(option.label, field.options.formValues) })
        : option)),
      modifiers: `${field.status} ${field.options.modifiers || ''}`,
    },
    events: {
      focus: field.options.onFocus,
      change: (value): void => onUserAction('input', value),
    },
  }),
  Radio: (field, onUserAction) => ({
    name: 'UIRadio',
    props: {
      id: field.id,
      name: field.id,
      label: field.label,
      value: field.value,
      helper: field.message,
      options: field.options.options.map((option: FormValue) => ((option.label !== undefined)
        ? ({ ...option, label: (field.i18n as FormValue)(option.label, field.options.formValues) })
        : option)),
      modifiers: `${field.status} ${field.options.modifiers || ''}`,
    },
    events: {
      focus: field.options.onFocus,
      change: (value): void => onUserAction('input', value),
    },
  }),
};

/**
 * Form field.
 */
export default Vue.extend<Generic, Generic, Generic, Props>({
  components: {
    UIRadio,
    UIButton,
    UIDropdown,
    UICheckbox,
    UITextarea,
    UITextfield,
    UIFileUploader,
  },
  props: {
    id: {
      type: String,
      required: true,
    },
    i18n: {
      type: Function,
      required: true,
    },
    type: {
      type: String,
      required: true,
    },
    label: {
      type: String,
      required: false,
      default: undefined,
    },
    status: {
      type: String,
      required: true,
    },
    message: {
      type: String,
      required: false,
      default: undefined,
    },
    value: { // eslint-disable-line vue/require-prop-types
      required: false,
      default: undefined,
    },
    options: {
      type: Object,
      required: true,
    },
    active: {
      type: Boolean,
      required: false,
      default: false,
    },
    customComponents: {
      type: Object,
      required: false,
      default: () => ({}),
    },
  },
  data() {
    return {
      isActive: this.active,
    };
  },
  computed: {
    allComponents() {
      return { ...builtInComponents, ...this.customComponents };
    },
    translatedLabel() {
      return (this.label !== undefined && this.label !== null)
        ? this.i18n(this.label, this.options.formValues)
        : null;
    },
    translatedMessage() {
      const helper = this.message || this.options.helper;
      return (helper !== undefined && helper !== null)
        ? this.i18n(helper, this.options.formValues)
        : null;
    },
    component() {
      // Unknown field type...
      if (this.allComponents[this.type] === undefined) {
        return null;
      }
      // Registered field type...
      return this.allComponents[this.type]({
        id: this.id,
        i18n: this.i18n,
        label: this.translatedLabel,
        type: this.type,
        options: { ...this.options, onFocus: this.focusField },
        message: this.translatedMessage,
        active: this.isActive,
        value: this.value,
        status: this.status,
      }, this.onUserAction);
    },
  },
  watch: {
    active() {
      this.isActive = this.active;
    },
  },
  methods: {
    onUserAction(type: 'click' | 'input', newValue: FormValue): void {
      this.$emit('userAction', { fieldId: this.id, type, value: newValue });
    },
    focusField(focusedValue: FormValue): void {
      this.isActive = true;
      if (this.options.onFocus !== undefined) {
        this.options.onFocus(focusedValue);
      }
    },
  },
});
</script>

// library/src/scripts/react/components/Field.tsx
/**
 * Copyright (c) Matthieu Jabbour. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

/* eslint-disable react/destructuring-assignment */

import {
  UIRadio,
  UIButton,
  UIDropdown,
  UICheckbox,
  UITextarea,
  UITextfield,
  UIFileUploader,
} from 'sonar-ui/react';
import * as React from 'react';
import PropTypes, { InferProps } from 'prop-types';
import fieldPropType from 'scripts/propTypes/field';
import Message from 'scripts/react/components/Message';
import { Field as FormField, FormValue } from 'scripts/core/Engine';

type OUA = (newValue: Json) => void;
type I18n = (label: string, values: Record<string, string>) => string;

export type Component = (field: FormField & { i18n: I18n; }, onUserAction: OUA) => JSX.Element;

export type Components = {
  [type: string]: Component;
};

const propTypes = {
  ...fieldPropType,
  onUserAction: PropTypes.func.isRequired,
  customComponents: PropTypes.objectOf(PropTypes.func.isRequired).isRequired,
};

const defaultProps = {};

/**
 * Built-in form components.
 */
const builtInComponents: Components = {
  Message: (field) => (
    <Message
      id={field.id}
      label={field.label}
      modifiers={`${field.status} ${field.options.modifiers || ''}`}
    />
  ),
  Button: (field, onUserAction) => (
    <UIButton
      id={field.id}
      label={field.label}
      icon={field.options.icon}
      type={field.options.type}
      iconPosition={field.options.iconPosition}
      onClick={(): void => onUserAction(true)}
      modifiers={`${field.status} ${field.options.modifiers || ''}`}
    />
  ),
  Textfield: (field, onUserAction) => (
    <UITextfield
      id={field.id}
      name={field.id}
      value={field.value}
      label={field.label}
      helper={field.message}
      min={field.options.min}
      max={field.options.max}
      onChange={onUserAction}
      step={field.options.step}
      icon={field.options.icon}
      size={field.options.size}
      type={field.options.type}
      onBlur={field.options.onBlur}
      onFocus={field.options.onFocus}
      maxlength={field.options.maxlength}
      transform={field.options.transform}
      onIconClick={field.options.onIconClick}
      autocomplete={field.options.autocomplete}
      iconPosition={field.options.iconPosition}
      debounceTimeout={field.options.debounceTimeout || 100}
      readonly={field.options.readonly || field.active === false}
      modifiers={`${field.status} ${field.options.modifiers || ''}`}
      placeholder={(field.options.placeholder !== undefined && field.options.placeholder !== null)
        ? field.i18n(field.options.placeholder, field.options.formValues)
        : null}
    />
  ),
  Textarea: (field, onUserAction) => (
    <UITextarea
      id={field.id}
      name={field.id}
      value={field.value}
      label={field.label}
      helper={field.message}
      onChange={onUserAction}
      cols={field.options.cols}
      rows={field.options.rows}
      onBlur={field.options.onBlur}
      onFocus={field.options.onFocus}
      maxlength={field.options.maxlength}
      transform={field.options.transform}
      autocomplete={field.options.autocomplete}
      debounceTimeout={field.options.debounceTimeout || 100}
      readonly={field.options.readonly || field.active === false}
      modifiers={`${field.status} ${field.options.modifiers || ''}`}
      placeholder={(field.options.placeholder !== undefined && field.options.placeholder !== null)
        ? field.i18n(field.options.placeholder, field.options.formValues)
        : null}
    />
  ),
  FileUploader: (field, onUserAction) => (
    <UIFileUploader
      id={field.id}
      name={field.id}
      label={field.label}
      helper={field.message}
      onChange={onUserAction}
      icon={field.options.icon}
      onFocus={field.options.onFocus}
      multiple={field.options.multiple}
      iconPosition={field.options.iconPosition}
      modifiers={`${field.status} ${field.options.modifiers || ''}`}
      placeholder={(field.options.placeholder !== undefined && field.options.placeholder !== null)
        ? field.i18n(field.options.placeholder, field.options.formValues)
        : null}
    />
  ),
  Dropdown: (field, onUserAction) => (
    <UIDropdown
      id={field.id}
      name={field.id}
      label={field.label}
      value={field.value}
      helper={field.message}
      onChange={onUserAction}
      icon={field.options.icon}
      onFocus={field.options.onFocus}
      options={field.options.options.map((option: Json) => ((option.type === 'option')
        ? ({ ...option, label: field.i18n(option.label, field.options.formValues) })
        : option))}
      multiple={field.options.multiple}
      modifiers={`${field.status} ${field.options.modifiers || ''}`}
    />
  ),
  Checkbox: (field, onUserAction) => (
    <UICheckbox
      id={field.id}
      name={field.id}
      label={field.label}
      value={field.value}
      helper={field.message}
      onChange={onUserAction}
      onFocus={field.options.onFocus}
      options={field.options.options.map((option: Json) => ((option.type === 'option')
        ? ({ ...option, label: field.i18n(option.label, field.options.formValues) })
        : option))}
      modifiers={`${field.status} ${field.options.modifiers || ''}`}
    />
  ),
  Radio: (field, onUserAction) => (
    <UIRadio
      id={field.id}
      name={field.id}
      label={field.label}
      value={field.value}
      helper={field.message}
      onChange={onUserAction}
      onFocus={field.options.onFocus}
      options={field.options.options.map((option: Json) => ((option.type === 'option')
        ? ({ ...option, label: field.i18n(option.label, field.options.formValues) })
        : option))}
      modifiers={`${field.status} ${field.options.modifiers || ''}`}
    />
  ),
};

/**
 * Form field.
 */
export default function Field(props: InferProps<typeof propTypes>): JSX.Element | null {
  const i18n = props.i18n as I18n;
  const { active } = props;
  const { value, status, options } = props;
  const { id, type, customComponents } = props;
  const allComponents: Components = { ...builtInComponents, ...customComponents };
  const label = React.useMemo(() => ((props.label !== undefined && props.label !== null)
    ? i18n(props.label, options.formValues)
    : null), [props.label]);
  const message = React.useMemo(() => {
    const helper = props.message || options.helper;
    return (helper !== undefined && helper !== null)
      ? i18n(helper, options.formValues)
      : null;
  }, [props.message, options.helper]);

  // The following lines prevent browsers auto-fill system from changing fields
  // located in other steps, resetting previous steps and breaking overall UX.
  const [isActive, setIsActive] = React.useState(active);

  React.useEffect(() => {
    setIsActive(active);
  }, [active]);

  const focusField = (focusedValue: FormValue): void => {
    setIsActive(true);
    if (options.onFocus !== undefined) {
      options.onFocus(focusedValue);
    }
  };

  const onUserAction = (newValue: FormValue): void => {
    props.onUserAction({ type: 'input', value: newValue, fieldId: id });
  };

  // Unknown field type...
  if (allComponents[type] === undefined) {
    return null;
  }
  // Registered field type...
  return allComponents[type]({
    id,
    type,
    label,
    message,
    active: isActive,
    i18n: i18n as I18n,
    value: value as FormValue,
    options: { ...options, onFocus: focusField },
    status: status as 'success' | 'error' | 'initial',
  }, onUserAction);
}

Field.propTypes = propTypes;
Field.defaultProps = defaultProps;
Field.displayName = 'Field';
