// library/src/scripts/vue/components/Step.vue
<template>
  <div :class="buildClass('gincko__step', [status, id, isActive ? 'active': ''])">
    <div class="gincko__step__fields">
      <!-- Key is composed of both step and field ids, in order to ensure each field is correctly
      reset when user changes his journey in previous steps.  -->
      <Field
        v-for="field in fields"
        :id="field.id"
        :key="field.id"
        :i18n="i18n"
        :active="isActive"
        :type="field.type"
        :label="field.label"
        :value="field.value"
        :status="field.status"
        :options="field.options"
        :message="field.message"
        :custom-components="customComponents"
        :all-values="allValues"
        @userAction="onUserAction"
      />
    </div>
  </div>
</template>

<script lang="ts">
/**
 * Copyright (c) Matthieu Jabbour. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import Vue from 'vue';
import { buildClass } from 'sonar-ui/vue';
import { Step } from 'scripts/propTypes/step';
import Field from 'scripts/vue/components/Field.vue';
import { AnyValue, UserAction } from 'scripts/core/Engine';
import { Field as FieldType } from 'scripts/propTypes/field';

type Generic = Record<string, AnyValue>;

interface Props extends Step {
  i18n: (label: string, values?: Record<string, string>) => string;
  customComponents: {
    [type: string]: (field: FieldType, onUserAction: (newValue: AnyValue) => void) => {
      name: string;
      props: AnyValue;
      events: AnyValue;
    };
  };
}

/**
 * Form step.
 */
export default Vue.extend<Generic, Generic, Generic, Props>({
  components: {
    Field,
  },
  props: {
    id: {
      type: String,
      required: true,
    },
    i18n: {
      type: Function,
      required: true,
    },
    index: {
      type: Number,
      required: true,
    },
    status: {
      type: String,
      required: true,
    },
    fields: {
      type: Array,
      required: true,
    },
    isActive: {
      type: Boolean,
      required: true,
    },
    customComponents: {
      type: Object,
      required: false,
      default: () => ({}),
    },
    allValues: {
      type: Object,
      required: true,
    },
  },
  methods: {
    onUserAction(userAction: UserAction): void {
      this.$emit('userAction', { ...userAction, stepIndex: this.index, stepId: this.id });
    },
    buildClass(baseClass: string, modifiers: string[]) {
      return buildClass(baseClass, modifiers);
    },
  },
});
</script>

// library/src/scripts/react/components/Step.tsx
/**
 * Copyright (c) Matthieu Jabbour. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import * as React from 'react';
import { InferProps } from 'prop-types';
import { buildClass } from 'sonar-ui/react';
import { UserAction } from 'scripts/core/Engine';
import stepPropType from 'scripts/propTypes/step';
import Field, { Components } from 'scripts/react/components/Field';

const defaultProps = {};

/**
 * Form step.
 */
export default function Step(props: InferProps<typeof stepPropType>): JSX.Element {
  const { i18n } = props;
  const { index, id, status } = props;
  const { fields, customComponents, isActive } = props;

  const onUserAction = (userAction: UserAction): void => {
    const fullUserAction: UserAction = { ...userAction, stepIndex: index as number, stepId: id };
    (props.onUserAction as (userAction: UserAction) => void)(fullUserAction);
  };

  return (
    <div className={buildClass('gincko__step', [status, id, isActive ? 'active' : ''])}>
      <div className="gincko__step__fields">
        {/* Key is composed of both step and field ids, in order to ensure each field is correctly
        reset when user changes his journey in previous steps. */}
        {fields.map((field) => (
          <Field
            i18n={i18n}
            id={field.id}
            active={isActive}
            key={`${id}_${field.id}`}
            type={field.type}
            label={field.label}
            value={field.value}
            status={field.status}
            options={field.options}
            message={field.message}
            onUserAction={onUserAction}
            allValues={props.allValues}
            customComponents={customComponents as Components}
          />
        ))}
      </div>
    </div>
  );
}

Step.propTypes = stepPropType;
Step.defaultProps = defaultProps;
Step.displayName = 'Step';
