// library/src/scripts/components/Field.tsx
/**
 * Copyright (c) Matthieu Jabbour. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

/* eslint-disable react/destructuring-assignment */

import {
  UIRadio,
  UIButton,
  markdown,
  buildClass,
  UIDropdown,
  UICheckbox,
  UITextfield,
  UIFileUploader,
} from 'sonar-ui/react';
import * as React from 'react';
import { Components } from 'scripts/types';
import PropTypes, { InferProps } from 'prop-types';
import fieldPropType from 'scripts/propTypes/field';

const propTypes = {
  ...fieldPropType,
  onUserAction: PropTypes.func.isRequired,
  customComponents: PropTypes.objectOf(PropTypes.func.isRequired).isRequired,
};

const defaultProps = {};

/**
 * Built-in form components.
 */
const builtInComponents: Components = {
  Message: (field) => {
    // We perform dynamic form values injection into message if necessary.
    let content = field.label || '';
    Object.keys(field.options.formValues || {}).forEach((key) => {
      content = content.replace(new RegExp(`{{${key}}}`, 'g'), field.options.formValues[key]);
    });
    return (
      <section
        id={field.id}
        // eslint-disable-next-line react/no-danger
        dangerouslySetInnerHTML={{ __html: markdown(content, false) }}
        className={buildClass('ui-message', `${field.status} ${field.options.modifiers || ''}`.split(' '))}
      />
    );
  },
  Button: (field, onUserAction) => (
    <UIButton
      id={field.id}
      label={field.label}
      icon={field.options.icon}
      type={field.options.type}
      iconPosition={field.options.iconPosition}
      onClick={(): void => onUserAction(field.id)}
      modifiers={`${field.status} ${field.options.modifiers || ''}`}
    />
  ),
  Textfield: (field, onUserAction) => (
    <UITextfield
      id={field.id}
      name={field.id}
      label={field.label}
      value={field.value}
      onChange={onUserAction}
      min={field.options.min}
      max={field.options.max}
      step={field.options.step}
      icon={field.options.icon}
      size={field.options.size}
      type={field.options.type}
      onBlur={field.options.onBlur}
      onFocus={field.options.onFocus}
      readonly={field.options.readonly || field.active === false}
      maxlength={field.options.maxlength}
      placeholder={field.options.placeholder}
      onIconClick={field.options.onIconClick}
      iconPosition={field.options.iconPosition}
      helper={field.message || field.options.helper}
      modifiers={`${field.status} ${field.options.modifiers || ''}`}
    />
  ),
  FileUploader: (field, onUserAction) => (
    <UIFileUploader
      id={field.id}
      name={field.id}
      label={field.label}
      onChange={onUserAction}
      icon={field.options.icon}
      onFocus={field.options.onFocus}
      multiple={field.options.multiple}
      placeholder={field.options.placeholder}
      iconPosition={field.options.iconPosition}
      helper={field.message || field.options.helper}
      modifiers={`${field.status} ${field.options.modifiers || ''}`}
    />
  ),
  Dropdown: (field, onUserAction) => (
    <UIDropdown
      id={field.id}
      name={field.id}
      label={field.label}
      value={field.value}
      onChange={onUserAction}
      icon={field.options.icon}
      onFocus={field.options.onFocus}
      options={field.options.options}
      multiple={field.options.multiple}
      helper={field.message || field.options.helper}
      modifiers={`${field.status} ${field.options.modifiers || ''}`}
    />
  ),
  Checkbox: (field, onUserAction) => (
    <UICheckbox
      id={field.id}
      name={field.id}
      label={field.label}
      value={field.value}
      onChange={onUserAction}
      onFocus={field.options.onFocus}
      options={field.options.options}
      helper={field.message || field.options.helper}
      modifiers={`${field.status} ${field.options.modifiers || ''}`}
    />
  ),
  Radio: (field, onUserAction) => (
    <UIRadio
      id={field.id}
      name={field.id}
      label={field.label}
      value={field.value}
      onChange={onUserAction}
      onFocus={field.options.onFocus}
      options={field.options.options}
      helper={field.message || field.options.helper}
      modifiers={`${field.status} ${field.options.modifiers || ''}`}
    />
  ),
};

/**
 * Form field.
 */
export default function Field(props: InferProps<typeof propTypes>): JSX.Element | null {
  // eslint-disable-next-line object-curly-newline
  const { label, active, value, status, options, message, id, type, customComponents } = props;
  const allComponents: Components = { ...builtInComponents, ...customComponents };

  // The following lines prevent browsers auto-fill system from changing fields
  // located in other steps, resetting previous steps and breaking overall UX.
  const [isActive, setIsActive] = React.useState(active);

  React.useEffect(() => {
    setIsActive(active);
  }, [active]);

  const focusField = (focusedValue: string | string[]): void => {
    setIsActive(true);
    if (options.onFocus !== undefined) {
      options.onFocus(focusedValue);
    }
  };

  const onUserAction = (newValue: string): void => {
    props.onUserAction(id, { type: 'input', value: newValue });
  };

  // Unknown field type...
  if (allComponents[type] === undefined) {
    return null;
  }
  // Registered field type...
  return allComponents[type]({
    id,
    label,
    type,
    options: { ...options, onFocus: focusField },
    message,
    active: isActive,
    value: value as string | string[],
    status: status as 'success' | 'error' | 'initial',
  }, onUserAction);
}

Field.propTypes = propTypes;
Field.defaultProps = defaultProps;
Field.displayName = 'Field';

// library/src/scripts/vue/components/Field.vue
<template>
  <component
    :is="component.name"
    v-if="component !== null"
    v-bind="component.props"
    v-on="Object.keys(component.events).reduce((events, event) => (
      (component.events[event] !== undefined)
        ? { ...events, [event]: component.events[event] }
        : events
    ), {})"
  />
</template>

<script lang="ts">
/**
 * Copyright (c) Matthieu Jabbour. All Rights Reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

/* eslint-disable vue/one-component-per-file */

import {
  Json,
  Field,
  Generic,
  FormValue,
} from 'scripts/types';
import {
  UIRadio,
  UIButton,
  markdown,
  buildClass,
  UIDropdown,
  UICheckbox,
  UITextarea,
  UITextfield,
  UIFileUploader,
} from 'sonar-ui/vue';
import Vue from 'vue';
import { ExtendedVue } from 'vue/types/vue.d';

type Components = { [type: string]: Component; };
type Component = (field: Field, onUserAction: (newValue: FormValue) => void) => Json;

interface Props {
  id: string;
  type: string;
  label: string;
  status: string;
  message: string;
  value: FormValue;
  options: Json;
  active: boolean;
  customComponents: {
    [type: string]: (field: Field, onUserAction: (newValue: FormValue) => void) => {
      name: string;
      props: Json;
      events: Json;
    };
  };
}

Vue.component('Message', {
  props: {
    id: {
      type: String,
      required: true,
    },
    label: {
      type: String,
      required: false,
      default: '',
    },
    status: {
      type: String,
      required: true,
    },
    options: {
      type: Object,
      required: true,
    },
  },
  computed: {
    content(): string {
      // We perform dynamic form values injection into message if necessary.
      let content = this.label || '';
      Object.keys(this.options.formValues || {}).forEach((key) => {
        content = content.replace(new RegExp(`{{${key}}}`, 'g'), this.options.formValues[key]);
      });
      return markdown(content, false);
    },
    className() {
      return buildClass('ui-message', `${this.status} ${this.options.modifiers || ''}`.split(' '));
    },
  },
  render(createElement) {
    return createElement('section', {
      attrs: {
        id: this.id,
        class: this.className,
      },
      domProps: {
        innerHTML: this.content,
      },
    });
  },
}) as ExtendedVue<Vue, Generic, Generic, Generic, Generic>;

/**
 * Built-in form components.
 */
const builtInComponents: Components = {
  Message: (field) => ({
    name: 'Message',
    props: {
      id: field.id,
      label: field.label,
      status: field.status,
      options: field.options,
    },
    events: {},
  }),
  Button: (field, onUserAction) => ({
    name: 'UIButton',
    props: {
      id: field.id,
      label: field.label,
      icon: field.options.icon,
      type: field.options.type,
      modifiers: `${field.status} ${field.options.modifiers || ''} `,
      iconPosition: field.options.iconPosition,
    },
    events: {
      click: (): void => onUserAction(field.id),
    },
  }),
  Textfield: (field, onUserAction) => ({
    name: 'UITextfield',
    props: {
      id: field.id,
      name: field.id,
      label: field.label,
      value: field.value,
      min: field.options.min,
      max: field.options.max,
      step: field.options.step,
      icon: field.options.icon,
      size: field.options.size,
      type: field.options.type,
      readonly: field.options.readonly || field.active === false,
      maxlength: field.options.maxlength,
      placeholder: field.options.placeholder,
      iconPosition: field.options.iconPosition,
      helper: field.message || field.options.helper,
      modifiers: `${field.status} ${field.options.modifiers || ''} `,
    },
    events: {
      change: onUserAction,
      focus: field.options.onFocus,
      blur: field.options.onBlur,
      iconClick: field.options.onIconClick,
    },
  }),
  Textarea: (field, onUserAction) => ({
    name: 'UITextarea',
    props: {
      id: field.id,
      name: field.id,
      label: field.label,
      value: field.value,
      cols: field.options.cols,
      rows: field.options.rows,
      maxlength: field.options.maxlength,
      placeholder: field.options.placeholder,
      autocomplete: field.options.autocomplete,
      helper: field.message || field.options.helper,
      readonly: field.options.readonly || field.active === false,
      modifiers: `${field.status} ${field.options.modifiers || ''}`,
    },
    events: {
      change: onUserAction,
      focus: field.options.onFocus,
      blur: field.options.onBlur,
    },
  }),
  FileUploader: (field, onUserAction) => ({
    name: 'UIFileUploader',
    props: {
      id: field.id,
      name: field.id,
      label: field.label,
      value: field.value,
      icon: field.options.icon,
      placeholder: field.options.placeholder,
      iconPosition: field.options.iconPosition,
      helper: field.message || field.options.helper,
      modifiers: `${field.status} ${field.options.modifiers || ''}`,
    },
    events: {
      change: onUserAction,
      focus: field.options.onFocus,
    },
  }),
  Dropdown: (field, onUserAction) => ({
    name: 'UIDropdown',
    props: {
      id: field.id,
      name: field.id,
      label: field.label,
      value: field.value,
      icon: field.options.icon,
      options: field.options.options,
      multiple: field.options.multiple,
      helper: field.message || field.options.helper,
      modifiers: `${field.status} ${field.options.modifiers || ''}`,
    },
    events: {
      change: onUserAction,
      focus: field.options.onFocus,
    },
  }),
  Checkbox: (field, onUserAction) => ({
    name: 'UICheckbox',
    props: {
      id: field.id,
      name: field.id,
      label: field.label,
      value: field.value,
      options: field.options.options,
      helper: field.message || field.options.helper,
      modifiers: `${field.status} ${field.options.modifiers || ''}`,
    },
    events: {
      change: onUserAction,
      focus: field.options.onFocus,
    },
  }),
  Radio: (field, onUserAction) => ({
    name: 'UIRadio',
    props: {
      id: field.id,
      name: field.id,
      label: field.label,
      value: field.value,
      options: field.options.options,
      helper: field.message || field.options.helper,
      modifiers: `${field.status} ${field.options.modifiers || ''}`,
    },
    events: {
      change: onUserAction,
      focus: field.options.onFocus,
    },
  }),
};

/**
 * Form field.
 */
export default Vue.extend<Generic, Generic, Generic, Props>({
  components: {
    UIRadio,
    UIButton,
    UIDropdown,
    UICheckbox,
    UITextarea,
    UITextfield,
    UIFileUploader,
  },
  props: {
    id: {
      type: String,
      required: true,
    },
    type: {
      type: String,
      required: true,
    },
    label: {
      type: String,
      required: false,
      default: '',
    },
    status: {
      type: String,
      required: true,
    },
    message: {
      type: String,
      required: false,
      default: '',
    },
    value: { // eslint-disable-line vue/require-prop-types
      required: false,
      default: undefined,
    },
    options: {
      type: Object,
      required: true,
    },
    active: {
      type: Boolean,
      required: false,
      default: false,
    },
    customComponents: {
      type: Object,
      required: false,
      default: () => ({}),
    },
  },
  data() {
    return {
      isActive: this.active,
    };
  },
  computed: {
    allComponents() {
      return { ...builtInComponents, ...this.customComponents };
    },
    component() {
      // Unknown field type...
      if (this.allComponents[this.type] === undefined) {
        return null;
      }
      // Registered field type...
      return this.allComponents[this.type]({
        id: this.id,
        label: this.label,
        type: this.type,
        options: { ...this.options, onFocus: this.focusField },
        message: this.message,
        active: this.isActive,
        value: this.value,
        status: this.status,
      }, this.onUserAction);
    },
  },
  watch: {
    active() {
      this.isActive = this.active;
    },
  },
  methods: {
    onUserAction(newValue: FormValue): void {
      this.$emit('userAction', this.id, { type: 'input', value: newValue });
    },
    focusField(focusedValue: FormValue): void {
      this.isActive = true;
      if (this.options.onFocus !== undefined) {
        this.options.onFocus(focusedValue);
      }
    },
  },
});
</script>
